version: '3.7'
services:
  proxy:
    image: nginx
    volumes:
      - ./share/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7778:7778"
  web:
    build: .
    volumes:
      - ./flag:/flag:ro
